### PR TITLE
Add a 'tests passing' badge for the main branch on README

### PR DESCRIPTION
**Pull request by gkokolatos**
This is a minor cosmetic addition. It feels useful to have the green stamp of approval on the front page.

### CODE REVIEW

**Review by rjuju — COMMENTED** [review]
Good idea.

I think (I haven't really checked) that most project put such badges first though.  That's maybe easier to read when using a standard text editor, and could make more sense if we ever add more badges (code coverage...).  What do you think?

**Review by rjuju — APPROVED** [review]
LGTM!

**Comment by gkokolatos** [comment]
> Good idea.

Thanks!

> I think (I haven't really checked) that most project put such badges first though. That's maybe easier to read when using a standard text editor, and could make more sense if we ever add more badges (code coverage...). What do you think?

Sure! I just moved it up. It is a distinct commit but it can be squashed during merging

**Comment by rjuju** [comment]
Thanks!  And agreed, I squashed both commits for a cleaner git history.

**Pull request merged**
