### PR TITLE
Add github actions tests

### PR DESCRIPTION
**Pull request by gkokolatos**
This is a basic setup for a CI based on github actions. It is currently executed only on main and PRs against it. It is run against postgres major versions [11-15] on an ubuntu 22.04.

It is a bit rough yet it works and is a decent base for extending in a later stage.

### CODE REVIEW

**Review by rjuju — COMMENTED** [review]
That's awesome, thanks a lot!

It looks way good enough to be merged, it can still be enhanced later if needed.  I just have one question: why use "postgres-major-XY" in a "version" array, since you only need the XY part anyway?  AFAICS the naming underneath stragery/matrix is free, so we could instead use "pg_major_version: [ 11, 12, ...]".  It would still be self explanatory be would avoid relying on `echo | cut` or anything else.

**Comment by gkokolatos** [comment]
> That's awesome, thanks a lot!

Thank you!

> It looks way good enough to be merged, it can still be enhanced later if needed. I just have one question: why use "postgres-major-XY" in a "version" array, since you only need the XY part anyway? AFAICS the naming underneath stragery/matrix is free, so we could instead use "pg_major_version: [ 11, 12, ...]". It would still be self explanatory be would avoid relying on `echo | cut` or anything else.

A very fair question. The honest answer is that I was uncertain on how it would be used while composing the file and did not focus on it during clean up. Let me push a new version :)

**Comment by gkokolatos** [comment]
Please find a new version of the code.

Besides substituting the matrix variable as recommended, it also adds code to print the specifics of the test failures from the test run. It most probably be useful to know the exact error that occurred.

**Review by rjuju — APPROVED** [review]
LGTM!

**Comment by rjuju** [comment]
Thanks a lot!  That looks like a great improvement.  I'm not saying that I can't wait to send a buggy PR, but almost :p

I'm wondering if it's possible to automatically get the list of major versions to avoid forgetting bumping it.  Unfortunately the only rss feed I know is https://www.postgresql.org/versions.rss and isn't suitable for that.  Anyway, that's not a blocker so I will merge your PR now!

**Comment by gkokolatos** [comment]
Thank you very much Julien!

Looking forward to see it in action :badatsum:

**Pull request merged**
